#!/bin/sh

set -e
command=$1

print_help() {
  echo "available commands: help, ls, set"
}

print_list() {
  ls $HOME/.py-prompts/themes | rev | cut -d "." -f 2- | rev
}

if [ -z $command ]; then
  print_help
  exit 1
fi

if [ "$command" = "help" ]; then
  print_help
  exit 0
fi

if [ "$command" = "ls" ]; then
  print_list
  exit 0
fi

if [ "$command" = "set" ]; then
  theme_name=$2
  if [ -z "$theme_name" ]; then
    echo "usage: py-prompts set <theme_name>"
    echo "available themes"
    print_list
  else
    echo "setting theme $theme_name"
    if [ ! -f "$HOME/.py-prompts/themes/$theme_name.py" ]; then
      echo "theme $theme_name does not exist. available themes are"
      print_list
      exit 1
    fi
    if [ -f $HOME/.bashrc ]; then
      echo "export PYTHONSTARTUP=$HOME/.py-prompts/themes/$theme_name.py" >> $HOME/.bashrc
    elif [ -f $HOME/.zshrc ]; then
      echo "export PYTHONSTARTUP=$HOME/.py-prompts/themes/$theme_name.py" >> $HOME/.zshrc
    else
      echo "could not detect your rc file. kindly add the following line in your rc file"
      echo "export PYTHONSTARTUP=$HOME/.py-prompts/themes/$theme_name.py" >> $HOME/.bashrc
    fi
  fi
  exit 0
fi

print_help
exit 1
